declare namespace NodeJS {
  interface ProcessEnv {
    PORT?: string;
    HOST?: string;
    TERMINAL_TOKEN_SECRET?: string;
    TERMINAL_TOKEN_TTL_SECONDS?: string;
    AI_CODING_PROFILER_ENABLED?: string;
    AI_CODING_PROFILER_OUTPUT_DIR?: string;
    AI_CODING_PROFILER_LAG_THRESHOLD_MS?: string;
    AI_CODING_PROFILER_POLL_INTERVAL_MS?: string;
    AI_CODING_PROFILER_CPU_MS?: string;
    AI_CODING_PROFILER_STALL_COOLDOWN_MS?: string;
    AI_CODING_PROFILER_SIGNALS_ENABLED?: string;
    AI_CODING_DEP_GRAPH_CACHE_TTL_MS?: string;
    AI_CODING_DB_TRACE_ENABLED?: string;
    AI_CODING_GIT_STATUS_CACHE_TTL_MS?: string;
    AI_CODING_TASK_DETAIL_INCLUDE_GIT_DEFAULT?: string;
    AI_CODING_TASK_DETAIL_INCLUDE_HEAVY_DEFAULT?: string;
    AI_CODING_PLAN_DETAIL_INCLUDE_HEAVY_DEFAULT?: string;
    AI_CODING_LOG_QUEUE_MAX_LINES?: string;
  }
}
